// Embeds ui/retrace.html into src/ui-html.ts so the UI ships inside the core package (Workers + Node).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "ui/retrace.html"), "utf8");
writeFileSync(join(root, "src/ui-html.ts"), `// GENERATED by scripts/embed-ui.mjs — edit ui/retrace.html instead.\nexport const UI_HTML = ${JSON.stringify(html)};\n`);
console.log("embedded ui:", html.length, "bytes");
