// Seeds a realistic Boxing-RPG build session into a Retrace store (local SQLite by default, or RETRACE_URL).
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
const t = new StdioClientTransport({ command: "node", args: ["packages/mcp-server/dist/index.js"], env: { ...process.env, RETRACE_PROJECT: "boxing-rpg", RETRACE_ACTOR: "claude-code", RETRACE_ACTOR_MODEL: "claude-fable-5", RETRACE_ON_BEHALF_OF: "jordan@slcwitit.com" } });
const c = new Client({ name: "seed", version: "0" }); await c.connect(t);
const call = async (name, args) => (await c.callTool({ name, arguments: args })).structuredContent;
const base = Date.parse("2026-08-16T14:00:00Z"); let i = 0; const ts = (min) => new Date(base + min * 60000).toISOString();
const ins = await call("retrace_instruct", { human_id: "jordan@slcwitit.com", instruction: "Add a jab counter to the fight loop and show it on the HUD", timestamp: ts(0), artifacts: [{ id: "task:jab-counter", kind: "task", label: "Jab counter feature" }] });
const r1 = await call("retrace_log", { action: "read", caused_by: ins.id, timestamp: ts(1), artifacts: [{ id: "repo:rpg#src/fight/loop.ts", kind: "file", label: "src/fight/loop.ts" }], intent: "understand where punches are resolved before editing", location: { path: "src/fight/loop.ts", system: "claude-code", environment: "local" }, method: { tool: "Read", automated: true, tokens: 2100 } });
const e1 = await call("retrace_log", { action: "edited", caused_by: ins.id, timestamp: ts(4), artifacts: [{ id: "repo:rpg#src/fight/loop.ts", kind: "file", label: "src/fight/loop.ts" }], intent: "increment jabCount when a punch of type 'jab' lands", change: { summary: "add jabCount to FightState; increment on landed jab", diff: "@@ -41,6 +41,9 @@\n   if (punch.landed) {\n+    if (punch.type === 'jab') state.jabCount++;\n     applyDamage(state, punch);\n   }" }, location: { path: "src/fight/loop.ts", system: "claude-code", environment: "local" }, method: { tool: "Edit", automated: true, tokens: 900 } });
const e2 = await call("retrace_log", { action: "created", caused_by: e1.id, timestamp: ts(7), artifacts: [{ id: "repo:rpg#src/ui/JabCounter.tsx", kind: "file", label: "src/ui/JabCounter.tsx", derived_from: ["repo:rpg#src/fight/loop.ts"] }], intent: "HUD widget that reads jabCount from FightState", location: { path: "src/ui/JabCounter.tsx", system: "claude-code", environment: "local" }, method: { tool: "Write", automated: true, tokens: 1400 } });
const x1 = await call("retrace_log", { action: "executed", caused_by: e2.id, timestamp: ts(9), artifacts: [{ id: "cmd:npm-test", kind: "command", label: "npm test" }], intent: "confirm nothing regressed", change: { summary: "42 passed, 0 failed" }, location: { system: "claude-code", environment: "local" }, method: { tool: "Bash", automated: true, params: { cmd: "npm test" } }, duration_ms: 8300 });
const ins2 = await call("retrace_instruct", { human_id: "jordan@slcwitit.com", instruction: "Nice — make the counter flash red on 3 straight jabs, coaches call that a 'triple'", timestamp: ts(12), artifacts: [{ id: "task:jab-counter", kind: "task", label: "Jab counter feature" }] });
const e3 = await call("retrace_log", { action: "edited", caused_by: ins2.id, timestamp: ts(15), artifacts: [{ id: "repo:rpg#src/ui/JabCounter.tsx", kind: "file", label: "src/ui/JabCounter.tsx" }], intent: "flash red when consecutiveJabs >= 3 (coach's 'triple')", change: { summary: "add consecutiveJabs tracking + red flash class" }, location: { path: "src/ui/JabCounter.tsx", system: "claude-code", environment: "local" }, method: { tool: "Edit", automated: true, tokens: 700 } });
await call("retrace_log", { action: "approved", timestamp: ts(22), actor: { type: "human", id: "jordan@slcwitit.com", display_name: "Jordan" }, caused_by: e3.id, artifacts: [{ id: "repo:rpg#pr/57", kind: "pr", label: "PR #57 jab counter" }], intent: "reviewed diff, played 3 rounds, feels right", location: { system: "github", url: "https://github.com/slcwitit/rpg/pull/57" }, method: { tool: "github-ui", automated: false } });
await call("retrace_log", { action: "executed", timestamp: ts(23), actor: { type: "system", id: "github-actions", display_name: "CI" }, caused_by: e3.id, artifacts: [{ id: "repo:rpg#pr/57", kind: "pr", label: "PR #57 jab counter" }], intent: "merge to main after green checks", change: { summary: "merged 3 files, +61 −4" }, location: { system: "github", environment: "ci" }, method: { tool: "actions/merge", automated: true } });
console.log((await c.callTool({ name: "retrace_verify", arguments: {} })).content[0].text);
await c.close(); process.exit(0);
